#ifndef _GATEWAY_STATUS_H_
#define _GATEWAY_STATUS_H_

typedef enum {
    GATEWAY_STATUS_WATING_FOR_A_MESSAGE,
    GATEWAY_STATUS_RECEPTED_LORALORA_MESSAGE_TRYING_ETHERNET,
    GATEWAY_STATUS_RECEPTED_LORAGNSS_MESSAGE_TRYING_ETHERNET,
    GATEWAY_STATUS_RECEPTED_LORALORA_MESSAGE_TRYING_MOBILE_NETWORK,
    GATEWAY_STATUS_RECEPTED_LORAGNSS_MESSAGE_TRYING_MOBILE_NETWORK,

    GATEWAY_STATUS_PARSE_ERROR
} gatewayStatus_t;

#endif // _GATEWAY_STATUS_H_