#ifndef _GATEWAY_STATUS_H_
#define _GATEWAY_STATUS_H_

typedef enum {
    GATEWAY_STATUS_GNSS_OBTAIN,
    GATEWAY_STATUS_GNSS_UNAVAILABLE,
    GATEWAY_STATUS_NONE_LOCALIZATION_MEAN_AVAILABLE,
    GATEWAY_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK, // GNSS OK MN OK
    GATEWAY_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK, // GNSS NOK MN OK
    GATEWAY_STATUS_GNSS_OBTAIN_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_TRYING_LORA,  // GNSS OK MN NOK
    GATEWAY_STATUS_GNSS_UNAVAILABLE_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_TRYING_LORA, // GNSS NOK MN NOK
    
    GATEWAY_STATUS_GNSS_LOADED_MESSAGE,  // RELOADED TYPE MESSAGE WITH GNSS INFO
    GATEWAY_STATUS_IMU_LOADED_MESSAGE,  // RELOADED TYPE MESSAGE WITH IMU INFO

    GATEWAY_STATUS_GNSS_UNAVAILABLE_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_LORA_UNAVAILABLE_GATHERING_INERTIAL_INFO, // GNSS NOK MN NOK LORA NOK
  
    GATEWAY_STATUS_GNSS_OBTAIN_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_LORA_UNAVAILABLE_SAVING_MESSAGE,  // GNSS OK MN NOK
    GATEWAY_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK_SAVING_MESSAGE,
    GATEWAY_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK_SAVING_MESSAGE,
    GATEWAY_STATUS_GNSS_UNAVAILABLE_CONNECTION_TO_MOBILE_NETWORK_UNAVAILABLE_LORA_UNAVAILABLE_GATHERED_INERTIAL_INFO_SAVING_MESSAGE,

    GATEWAY_STATUS_PARSE_ERROR
} gatewayStatus_t;

#endif // _GATEWAY_STATUS_H_