#ifndef _GATEWAY_STATUS_H_
#define _GATEWAY_STATUS_H_

typedef enum {
    GATEWAY_STATUS_GNSS_OBTAIN,
    GATEWAY_STATUS_GNSS_UNAVAILABLE,
    GATEWAY_STATUS_NONE_LOCALIZATION_MEAN_AVAILABLE,
    GATEWAY_STATUS_GNSS_OBTAIN_CONNECTED_TO_MOBILE_NETWORK,
    GATEWAY_STATUS_GNSS_UNAVAILABLE_CONNECTED_TO_MOBILE_NETWORK
} gatewayStatus_t;

#endif // _GATEWAY_STATUS_H_